### ISSUE TITLE
Education Page: Globe Feature

### ISSUE THREAD

**Issue by kimayamcolaco** [rise-summer/team-3-now#2]
Implement a movable globe feature as close to wireframe designs as possible
- Look for API to get movable globe: Look into possible existing features or APIs that you can pull from. I would suggest starting with looking for globe/map components within UI frameworks associated with react. Try looking for a globe that a user can interact with, but if this is not possible we can look for a map or similar feature instead
- Implement interactive capability: Whichever feature you decide to go with, try to implement it so a user can interact with it. If it is a globe, it should be rotatable, if it is a map maybe think about being able to zoom in or some other interactive ability
- Marker to show location of the cause: Have a marker that will show the location of the cause the page is associated with. For now this can be hardcoded to any place you want! Try looking for APIs that are able to show locations on maps/globes (geolocation API might be a possible option)

**Comment by dnaliu** [comment]
- Implemented WebGL Earth API, working on Android, currently not working on IOS devices
- Implemented interactive capability: globe rotates 360 degrees continuously
- Marker is implemented correctly to show location of the cause
* Working on IOS functionality
